{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "create"
	},
	"OnFailure": "/demoTahaApp/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/demoTahaApp/Actions/CreateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "SalesOrderHeaders",
		"Service": "/demoTahaApp/Services/com_sap_edm_sampleservice_v4.service"
	},
	"Properties": {
		"CreatedAt": "#Page:SalesOrderHeaders_Create/#Control:CreatedAt/#Value",
		"CurrencyCode": "#Page:SalesOrderHeaders_Create/#Control:CurrencyCode/#Value",
		"GrossAmount": "#Page:SalesOrderHeaders_Create/#Control:GrossAmount/#Value",
		"LifeCycleStatus": "#Page:SalesOrderHeaders_Create/#Control:LifeCycleStatus/#Value",
		"LifeCycleStatusName": "#Page:SalesOrderHeaders_Create/#Control:LifeCycleStatusName/#Value",
		"NetAmount": "#Page:SalesOrderHeaders_Create/#Control:NetAmount/#Value",
		"TaxAmount": "#Page:SalesOrderHeaders_Create/#Control:TaxAmount/#Value"
	}
}