{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "Customers_UpdateEntity"
	},
	"OnFailure": "/demoTahaApp/Actions/Customers/UpdateCustomerEntityFailureMessage.action",
	"OnSuccess": "/demoTahaApp/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/demoTahaApp/Services/com_sap_edm_sampleservice_v4.service",
		"EntitySet": "Customers",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"EmailAddress": "#Page:Customres_edits/#Control:FCEmail/#Value",
		"FirstName": "#Page:Customres_edits/#Control:FCFirstName/#Value",
		"LastName": "#Page:Customres_edits/#Control:FCLastName/#Value",
		"PhoneNumber": "#Page:Customres_edits/#Control:FCPhone/#Value"
	}
}